export const FARM_CATEGORY = [
  {
    companyId: 16,
    name: "Alpakka Enghaugen",
    category: {
      alpacaSales: false,
      alpacaWalking: false,
      bookable: false,
      shop: false,
      overnightStay: false,
      private: true,
      public: false,
      studServices: true,
    },
  },
  {
    companyId: 30,
    name: "Alpakka Norge",
    category: {
      alpacaSales: true,
      alpacaWalking: false,
      bookable: false,
      shop: false,
      overnightStay: false,
      private: false,
      public: true,
      studServices: true,
    },
  },
  {
    companyId: 31,
    name: "Alpakka Sigdal",
    category: {
      alpacaSales: false,
      alpacaWalking: false,
      bookable: false,
      shop: true,
      overnightStay: false,
      private: false,
      public: true,
      studServices: false,
    },
  },
  {
    companyId: 61,
    name: "Alpakkahagen",
    category: {
      alpacaSales: true,
      alpacaWalking: true,
      bookable: true,
      shop: true,
      overnightStay: false,
      private: false,
      public: true,
      studServices: false,
    },
  },
  {
    companyId: 28,
    name: "Lundegård Alpakka",
    category: {
      alpacaSales: true,
      alpacaWalking: true,
      bookable: true,
      shop: true,
      overnightStay: false,
      private: false,
      public: true,
      studServices: true,
    },
  },
  {
    companyId: 120,
    name: "Oddan Alpakka",
    category: {
      alpacaSales: true,
      alpacaWalking: true,
      bookable: true,
      shop: true,
      overnightStay: true,
      private: false,
      public: true,
      studServices: false,
    },
  },
  {
    companyId: 29,
    name: "Øyslebø Alpakka",
    category: {
      alpacaSales: false,
      alpacaWalking: false,
      bookable: true,
      shop: true,
      overnightStay: false,
      private: false,
      public: true,
      studServices: true,
    },
  },
];
