export const PUBLIC_FARMS = [
  "Alpakka Skåbu",
  "Alpakkahagen",
  "Alpakkalia Erik Brenna",
  "Nittedal alpakka",
  "Bergvang AS",
  "Alpakka Bromma",
  "Lundegård Alpakka",
  "Fjellgla Alpakka",
  "Alpakka Lista",
  "Alpakka Enghaugen",
  "Lille Alpakka",
  "Tønsbergs Alpakka",
  "Alpakka Syltøy",
  "Alpakka Sigdal",
  "Midt-Tjore gård",
  "Åmøy alpakkagård",
  "Alpakka Norefjell",
  "Skognes Gård",
  "Alpakka Norge",
  "Haugfoss Alpakka",
  "Alpakkaspinneriet",
  "Sørflaen Gård",
  "Varden Alpakkagård",
  "Alpakka Gausdal Bergseng DA",
  "Alpakka Fyresdal",
  "Oddan Alpakka",
  "Øyslebø Alpakka",
  "Norvetia Alpakka",
];
